#!/usr/bin/env bash
#
# Summary: copy folder from device to local
#
# Usage: android-cli device-backup <recipient-file> <backup-folder>
#

set -e # exit on error

recipient_file=${1}
target_folder=${2}

base_folder="/sdcard/"

while read cp_pattern
do
  echo "copio cartella: ${base_folder}${cp_pattern} in:  $target_folder"
  adb pull -a ${base_folder}${cp_pattern} $target_folder
done < $recipient_file


# example: bash backup.bash alice.list alice

