#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: android-cli help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help android-cli
fi

lasher _help android-cli "$command"
