#!/usr/bin/env bash
#
# Summary: copy folder from device to local
#
# Usage: android-cli device-backup-termux <recipient-file> <backup-folder>
#

set -e # exit on error

recipient_file=${1:-"backup_list.txt"}
target_folder=${2:-"."}
phone_ip=${3:-"192.168.1.8"}
phone_port=${4:-"8022"}

base_folder="/sdcard/"

rm -f /tmp/backup_list.txt
tmpfile=$(mktemp /tmp/backup_list.txt)

scp -P ${phone_port} ${phone_ip}:/sdcard/${recipient_file} $tmpfile

while read cp_pattern
do
  echo "copio cartella: ${base_folder}${cp_pattern} in:  $target_folder"
  scp -P ${phone_port} -r ${phone_ip}:${base_folder}${cp_pattern} $target_folder
done < $tmpfile

rm -f $tmpfile
