#!/usr/bin/env bash
#
# Summary: copy folder from local to device
#
# Usage: android-cli device-restore <recipient-file> <backup-folder>
#

set -e # exit on error

recipient_file=${1}
target_folder="/sdcard/"
base_folder=${2}

while read cp_pattern
do
  folder=${base_folder}/${cp_pattern}
  if [ -d "$folder" ]; then
    echo "copio cartella: ${folder} in:  $target_folder"
    adb push ${folder} $target_folder
  else
    echo "folder not founded: ${folder} skip ..."
  fi
done < $recipient_file


# example: bash restore.bash alice.list alice
