#!/usr/bin/env bash
#
# Summary: remove package from device via adb
#
# Usage: android-cli adb-rm-package <package-id>
#

set -e # exit on error

error() { clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;}

packageid="$1"

[ -z "${packageid}" ] && error "packageid is required"

adb shell pm uninstall -k "${packageid}"


